### ISSUE TITLE
show button is not working

### ISSUE THREAD

**Issue by kota-yata** [pazguille/github-card#20]
[Toppage](http://pazguille.github.io/github-card/) is correctly working, but once I insert my username, [it](http://pazguille.github.io/github-card/?user=kota-yata) isn't working. I guess the parameter cause some bugs

**Comment by kota-yata** [comment]
Error message on Chrome

> Uncaught TypeError: doc.registerElement is not a function

**Comment by pazguille** [comment]
Fixed!
